spring:
  application:
    name: bank-cards-management

  # Database Configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bankcards_db}
    username: ${SPRING_DATASOURCE_USERNAME:bankcards_user}
    password: ${SPRING_DATASOURCE_PASSWORD:bankcards_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: none  # Liquibase handles schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    show-sql: false  # Set to true for development
    open-in-view: false

  # Liquibase Configuration
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
    enabled: true

  # Security Configuration
  security:
    jwt:
      secret-key: ${SPRING_SECURITY_JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: ${SPRING_SECURITY_JWT_EXPIRATION:86400000}  # 24 hours
      refresh-expiration: ${SPRING_SECURITY_JWT_REFRESH_EXPIRATION:604800000}  # 7 days

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: false

# Application-specific Configuration
app:
  security:
    encryption:
      algorithm: AES
      key: ${ENCRYPTION_KEY:ThisIsASecretKeyForCardEncryption32}
    cors:
      allowed-origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:4200}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
  
  card:
    default-limit: 100000.00
    max-transfer-amount: 50000.00
    min-balance: 0.00
  
  pagination:
    default-page-size: 20
    max-page-size: 100

# Logging Configuration
logging:
  level:
    root: INFO
    com.example.bankcards: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/bankcards.log
    max-size: 10MB
    max-history: 30

# Management Endpoints (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized